import { formatFindings, type FindingsSnapshot } from '../features/incidents/incident-findings-types'
import type { AiAnalysis } from '../features/incidents/incident-ai-types'
import type { ReferenceResult } from '../features/incidents/incident-reference-types'
export function emailReferenceExcerpt(excerpt: string): string {
  const compact = excerpt.replace(/\s+/g, ' ').trim()
  return compact.length > 320 ? `${compact.slice(0, 320)}… [Excerpt shortened; open the source for full context.]` : compact
}
export function formatEmailReport(incident: { recordId: string; createdAt: string; data: { title: string; rawLog: string } }, ai: AiAnalysis | undefined, references: ReferenceResult | undefined, includeLogs: boolean, findings?: FindingsSnapshot): string {
  const lines = ['Incident handoff', '', incident.data.title, `Incident ID: ${incident.recordId}`, `Created: ${incident.createdAt}`, '', 'This handoff contains saved results captured when the draft was prepared. Later investigation updates are not reflected in this email.', '', 'AI analysis']
  if (ai) {
    lines.push(ai.summary, `Model: ${ai.model}`, `Analysis saved: ${ai.generatedAt}`, '', 'Log evidence')
    lines.push(...(ai.evidence.length ? ai.evidence.map((item) => `[line ${item.line}] ${item.quote}`) : ['No specific evidence identified.']))
    lines.push('', 'AI-generated hypotheses', 'These hypotheses were generated by AI. See Investigation findings below for recorded human judgments.')
    lines.push(...(ai.hypotheses.length ? ai.hypotheses.map((item, index) => `Hypothesis ${index + 1}: ${item.explanation} (Evidence lines: ${item.evidenceLines.length ? item.evidenceLines.join(', ') : 'none cited'})`) : ['No hypotheses were identified in the saved AI analysis.']))
    lines.push('', 'AI-suggested checks', ...(ai.suggestedChecks.length ? ai.suggestedChecks.map((item) => `- ${item}`) : ['No checks were suggested in the saved AI analysis.']))
  } else lines.push('No completed AI analysis was available when this draft was prepared.')
  lines.push('', formatFindings(findings))
  lines.push('', 'Troubleshooting references')
  if (references) {
    lines.push(`Search: ${references.query}`, `Search saved: ${references.searchedAt}`)
    lines.push(...(references.items.length ? references.items.flatMap((item) => [`- ${item.title}`, item.url, emailReferenceExcerpt(item.excerpt), '']) : ['No references found.']))
  } else lines.push('No completed reference search was available when this draft was prepared.')
  lines.push('', includeLogs ? 'Original logs' : 'Full original logs omitted. AI evidence and human judgment reasons may contain log excerpts.')
  if (includeLogs) lines.push(incident.data.rawLog)
  lines.push('', 'Reading this handoff', 'Human judgments apply to individual hypotheses and reflect the recorded assessment and supporting reason. A Confirmed judgment does not by itself establish the complete root cause or mean the incident is resolved. Hypotheses without a recorded judgment remain unreviewed. External references are troubleshooting resources, not evidence that a hypothesis is correct.')
  return lines.join('\n')
}
