import type { AiAnalysis } from '../features/incidents/incident-ai-types'
import type { FindingsSnapshot } from '../features/incidents/incident-findings-types'
import type { ReferenceResult } from '../features/incidents/incident-reference-types'
import { emailReferenceExcerpt } from './incident-email-content'

// All variable text is escaped; only this template supplies HTML and styles.
const escapeHtml = (text: string) => text.replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!)
const paragraph = (text: string) => `<p style="margin:8px 0;white-space:pre-wrap;overflow-wrap:anywhere">${escapeHtml(text)}</p>`
const label = (name: string, text: string) => `<p style="margin:6px 0;white-space:pre-wrap;overflow-wrap:anywhere"><strong>${escapeHtml(name)}:</strong> ${escapeHtml(text)}</p>`
const list = (items: string[]) => `<ul style="padding-left:22px;margin:12px 0">${items.map((text) => `<li style="margin:8px 0;white-space:pre-wrap;overflow-wrap:anywhere">${escapeHtml(text)}</li>`).join('')}</ul>`
const section = (title: string, content: string) => `<h2 style="font-size:18px;line-height:1.4;margin:28px 0 10px;color:#222">${escapeHtml(title)}</h2>${content}`
const group = (content: string) => `<div style="margin:16px 0 22px">${content}</div>`
function sourceLink(title: string, url: string) {
  try {
    const parsed = new URL(url)
    if (['https:', 'http:'].includes(parsed.protocol) && !parsed.username && !parsed.password) return `<a href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer" style="color:#245e9b;font-weight:600;overflow-wrap:anywhere">${escapeHtml(title)}</a>`
  } catch { /* Invalid URLs remain inert text. */ }
  return paragraph(title) + paragraph(url)
}

export function formatEmailHtml(incident: { recordId: string; createdAt: string; data: { title: string; rawLog: string } }, ai: AiAnalysis | undefined, references: ReferenceResult | undefined, includeLogs: boolean, snapshot?: FindingsSnapshot): string {
  const findings = snapshot?.findings ?? []
  const parts = [
    '<p style="font-size:13px;color:#555;margin:0 0 8px">IncidentDesk · Incident handoff</p>',
    `<h1 style="font-size:22px;line-height:1.4;margin:0 0 20px;overflow-wrap:anywhere">${escapeHtml(incident.data.title)}</h1>`,
    section('Summary', paragraph(ai?.summary ?? 'No completed AI analysis was available when this draft was prepared.') + (ai ? '<p style="font-size:12px;color:#536777">AI-generated summary</p>' : '')),
    section('Investigation findings', paragraph('Recorded human judgments for individual hypotheses. A Confirmed judgment does not by itself establish the complete root cause or mean the incident is resolved.') + (findings.length ? findings.map((f) => group(
      `<h3 style="font-size:16px;margin:0 0 8px">Hypothesis ${f.hypothesisIndex + 1} · ${escapeHtml(f.status)}</h3>` + paragraph(f.explanation) + label('Evidence and reason', f.reason) + label('Judged by', `${f.actorName} (${f.actorId})`) + label('Judged at', `${f.judgedAt} · Revision ${f.sequence}`)
    )).join('') : paragraph(snapshot ? 'No human judgments recorded for this analysis version.' : 'No completed AI analysis was available for investigation findings.'))),
  ]
  if (ai) {
    parts.push(section('AI-generated hypotheses', paragraph('These hypotheses were generated by AI. Recorded human judgments appear in Investigation findings above.') + (ai.hypotheses.length ? ai.hypotheses.map((h, index) => group(`<h3 style="font-size:16px;margin:0 0 8px">Hypothesis ${index + 1}</h3>` + paragraph(h.explanation) + label('Evidence lines', h.evidenceLines.length ? h.evidenceLines.join(', ') : 'none cited'))).join('') : paragraph('No hypotheses were identified in the saved AI analysis.'))))
    parts.push(section('AI-suggested checks', ai.suggestedChecks.length ? list(ai.suggestedChecks) : paragraph('No checks were suggested in the saved AI analysis.')))
    parts.push(section('Log evidence', ai.evidence.length ? list(ai.evidence.map((e) => `[line ${e.line}] ${e.quote}`)) : paragraph('No specific evidence identified.')))
  }
  parts.push(section('Troubleshooting references', paragraph('Resources for investigation; inclusion does not verify a hypothesis.') + (references ? label('Search', references.query) + (references.items.length ? references.items.map((r) => group(sourceLink(r.title, r.url) + paragraph(emailReferenceExcerpt(r.excerpt)))).join('') : paragraph('No references found.')) : paragraph('No completed reference search was available when this draft was prepared.'))))
  parts.push(section('Original logs', includeLogs ? `<pre style="white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.6 monospace;margin:12px 0">${escapeHtml(incident.data.rawLog)}</pre>` : paragraph('Full original logs omitted. AI evidence and human judgment reasons may contain log excerpts.')))
  parts.push(section('Snapshot details', paragraph('Saved results captured when this draft was prepared. Later investigation updates are not reflected in this email. Hypotheses without a recorded judgment remain unreviewed.') + label('Incident ID', incident.recordId) + label('Incident created', incident.createdAt) + (ai ? label('AI model', ai.model) + label('Analysis saved', ai.generatedAt) : '') + (snapshot ? label('Analysis version', snapshot.analysisVersion) : '') + (references ? label('Search saved', references.searchedAt) : '')))
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:16px;color:#222;background:#fff;font:14px/1.6 Arial,Helvetica,sans-serif">${parts.join('')}</body></html>`
}
